spring.application.name=HospitalManagement

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true

#spring.jpa.defer-datasource-initialization= true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql

server.servlet.context-path=/api/v1
jwt.secretKey=asdfhads9f67as98dfyaisudhfa98s67dfy89aishudfuays89dfyasi8df7asdf87987g98a7sg986a89sdf7y